apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-postgresql-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: microk8s-hostpath
